parameter = {
    "all_wheels_on_track": True,
    "x": 0.0,
    "y": 0.0,
    "closest_objects": [0, 0],
    "closest_waypoints": [0, 0],
    "distance_from_center": 0.0,
    "is_crashed": False,
    "is_left_of_center": False,
    "is_offtrack": False,
    "is_reversed": False,
    "heading": float,
    "objects_distance": [],
    "objects_heading": [],
    "objects_left_of_center": [],
    "objects_location": [],
    "objects_speed": [],
    "progress": 0.0,
    "speed": 2.0,
    "steering_angle": 0.0,
    "steps": 1,
    "track_length": 100.0,
    "track_width": 0.0,
    "waypoints": []
}
